### ISSUE TITLE
agregar mensaje de erro cuando en operation manager editando un operation presionan el botón de menos para quitar un equipment

### ISSUE THREAD

**Issue by dcanessa** [dcanessa/Proyecto-Boston#54]

**Comment by melvinitcr** [comment]
este issue esta complicado de resolver, el gridview que aparece a la hora de editar, se llena con los datos que ya estan en la base, y a ese mismo gridview le pueden agregar mas equipments

**Comment by melvinitcr** [comment]
se puede borrar de ese gridview pero igual en la base no cambia nada, es solo grafico
