### ISSUE TITLE
Cuando se actualiza un router mantener el valor que tiene en los dropdown

### ISSUE THREAD

**Issue by dcanessa** [dcanessa/Proyecto-Boston#72]

**Comment by melvinitcr** [comment]
El metodo tiene errores: getRouterUpdateData

-Se esta retornando una lista , se ocupa un único view
-Los datos que retorna están mal, por ejemplo si el router tiene un Operation Status que se llama "preheat", se esta retornando uno que se llama "Precalentar"
-Se ocupa retornar OperationStatusId y RouterStatusId en el mismo View
