### ISSUE TITLE
Eliminar mancomunado (Todos, Recipe,Upn,Reportes Donde Salga Recipes)

### ISSUE THREAD

**Issue by euw15** [dcanessa/Proyecto-Boston#76]
Esto hay que verlo en Recipe y Upn que salgan todas las recetas de nuevo

**Comment by dcanessa** [comment]
RecipeView: quitar los 2 usuarios y enable usuarios, solo queda el enable general, esto para getrecipeData, searchRecipe, searchRecipeByOperation

RecipeInsertView: quitar el firstUserLogin y agregar el recipeEnable

RecipeUpdateView: quitar los 2 enable de los usuarios, queda solo recipeEnable

Update second enable (método): ya no existe
