### ISSUE TITLE
 Modificar de reportes

### ISSUE THREAD

**Issue by euw15** [dcanessa/Proyecto-Boston#77]
- Reporte Recipe, agregar columnas Temperatura, Tiempo, Tiempo Enfriamiento
	- Reporte Recipe, Ocultar columna Recipe
	- Reporte Recipe, Mover columnas Process Recipe y Product para que sean las 2 primeras de la tabla
	- Reporte Recipe, Cambiar nombre Process Recipe por Recipe
	- Reporte UPN, Cambiar Recipe Process Id por Recipe
	(Todos estos cambios es para unificar el numero de la receta y sea el mismo que se muestra en Recipes Manager)

**Comment by melvinitcr** [comment]
Solo falta que se devuelva Temperatura, Tiempo, Tiempo Enfriamiento por cada recipe
